### ISSUE TITLE
python error for stellar-core-prometheus-exporter.py

### ISSUE THREAD

**Issue by thespamer** [stellar/packages#110]
I'm using:
stellar/stellar-core-prometheus-exporter:latest

...and defined the environment:
STELLAR_CORE_ADDRESS	= http://(my-stellar-core-ip):11626
PORT=9000

When grafana datasources tries to connect to python:
![Captura de Tela 2019-12-20 às 18 11 18](https://user-images.githubusercontent.com/46322485/71293617-c48cac80-2354-11ea-802b-e67b0d1a915c.png)
root@testnet-prometheus-stellar-core:/# python  /usr/bin/stellar-core-prometheus-exporter.py
---

Exception happened during processing of request from ('10.142.0.15', 60572)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/usr/bin/stellar-core-prometheus-exporter2.py", line 228, in do_GET
    g.labels(*self.labels).set(tmp[metric])
KeyError: 'delayed'
---

**Comment by thespamer** [comment]
this bug happens only on 10.0.0 or 10.0.0-gcloud satoshipay images.
fix; use satoshipay/stellar-core instead.
